apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 2  # HA를 위해 2개로 증가
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      # Pod Anti-affinity 추가 - 파드들이 다른 노드에 분산
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: keycloak
              topologyKey: kubernetes.io/hostname
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0.5
        args: ["start-dev"]  # 개발 모드
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: admin-password
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          value: "jdbc:postgresql://sangsangplus-postgre-server.postgres.database.azure.com:5432/keycloak_db?sslmode=require"
        - name: KC_DB_USERNAME
          value: "sangsangplus_admin"
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: azure-db-password
        # - name: KC_HOSTNAME
        #   value: "oauth.buildingbite.com"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_PROXY
          value: "edge"
        - name: KC_HTTP_HEADER_X_FRAME_OPTIONS
          value: "ALLOW-FROM https://oauth.buildingbite.com"
        - name: KC_HTTP_HEADER_CONTENT_SECURITY_POLICY
          value: "frame-ancestors 'self' https://oauth.buildingbite.com"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "400Mi"
            cpu: "20m"
          limits:
            memory: "500Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# HorizontalPodAutoscaler for Keycloak
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keycloak
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
# PodDisruptionBudget for Keycloak
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keycloak