#!/bin/bash

echo "=== SangSang Plus Gateway 배포 가이드 ==="
echo ""
echo "1. Secret 생성 (JWT_SECRET 필수, OAuth는 선택)"
echo "   kubectl create secret generic gateway-secrets \\"
echo "     --from-literal=jwt-secret='your-super-secret-jwt-key' \\"
echo "     --from-literal=google-client-id='your-google-client-id' \\"
echo "     --from-literal=google-client-secret='your-google-client-secret'"
echo ""
echo "2. 배포 적용"
echo "   kubectl apply -f k8s-deployment.yaml"
echo ""
echo "3. 배포 상태 확인"
echo "   kubectl get pods -l app=sangsang-plus-gateway"
echo "   kubectl get svc sangsang-plus-gateway"
echo ""
echo "4. 로그 확인"
echo "   kubectl logs -f deployment/sangsang-plus-gateway"
echo ""
echo "=== 환경변수 설정 가이드 ==="
echo ""
echo "필수 환경변수:"
echo "- JWT_SECRET: JWT 토큰 서명용 비밀키 (Secret으로 관리)"
echo ""
echo "선택 환경변수:"
echo "- KAFKA_BOOTSTRAP_SERVERS: Kafka 브로커 주소 (기본값: kafka:9092)"
echo "- USER_SERVICE_URL: User 서비스 URL (기본값: http://user-service:8081)"
echo "- GOOGLE_CLIENT_ID: Google OAuth 클라이언트 ID"
echo "- GOOGLE_CLIENT_SECRET: Google OAuth 클라이언트 시크릿"
echo ""
echo "=== 네트워크 설정 ==="
echo ""
echo "- 게이트웨이 포트: 8080"
echo "- Kafka 연결: kafka:9092 (같은 네임스페이스 내)"
echo "- User 서비스 연결: user-service:8081 (같은 네임스페이스 내)"