apiVersion: apps/v1
kind: Deployment
metadata:
  name: sangsang-plus-gateway
  labels:
    app: sangsang-plus-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sangsang-plus-gateway
  template:
    metadata:
      labels:
        app: sangsang-plus-gateway
    spec:
      containers:
      - name: gateway
        image: buildingbite/sangsangplus-gateway:latest
        ports:
        - containerPort: 8080
        env:
        # Kafka 설정 - 외부 Kafka 접근을 위한 설정
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "host.docker.internal:9092"  # Docker Desktop에서 호스트 접근
          # 또는 실제 Kafka 서버의 IP 주소 사용
          # value: "192.168.1.100:9092"
        
        # User 서비스 URL
        - name: USER_SERVICE_URL
          value: "http://user-service:8081"
        
        # JWT Secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: gateway-secrets
              key: jwt-secret
        
        # Google OAuth 설정 (선택사항)
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: gateway-secrets
              key: google-client-id
              optional: true
        
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gateway-secrets
              key: google-client-secret
              optional: true
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sangsang-plus-gateway
spec:
  selector:
    app: sangsang-plus-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# External Service for Kafka (k8s 외부의 Kafka에 접근하기 위한 설정)
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ExternalName
  externalName: host.docker.internal  # Docker Desktop의 경우
  # externalName: kafka.external.com  # 실제 외부 Kafka 도메인
  ports:
  - port: 9092
    targetPort: 9092
---
# Secret 생성 예시
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
type: Opaque
stringData:
  jwt-secret: "your-super-secret-jwt-key-change-this"
  google-client-id: "your-google-client-id"
  google-client-secret: "your-google-client-secret"