server:
  port: 8080
  netty:
    # SSE를 위한 Netty 서버 설정
    idle-timeout: 120s  # idle 연결 타임아웃
    connection-timeout: 10s  # 연결 타임아웃

spring:
  application:
    name: gateway-service
  main:
    web-appliㅇcation-type: reactive
  
  cloud:
    gateway:
      httpclient:
        # SSE를 위한 타임아웃 설정
        connect-timeout: 5000  # 연결 타임아웃 5초
        response-timeout: 120s  # 응답 타임아웃 120초 (SSE는 긴 연결)
        pool:
          type: elastic  # 탄력적 연결 풀 사용
          max-idle-time: 10s
        # WebSocket/SSE를 위한 설정
        wiretap: false  # 디버깅 비활성화로 성능 향상
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://buildingbite.com"
              - "https://oauth.buildingbite.com"
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service.sangsangplus-backend.svc.cluster.local}
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuth

        - id: auth-users-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/users/**
          filters:
            - JwtAuth
            
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://product-service.sangsangplus-backend.svc.cluster.local}
          predicates:
            - Path=/api/products/**
          filters:
            - JwtAuth
        
        - id: review-service
          uri: ${REVIEW_SERVICE_URL:http://review-service.sangsangplus-backend.svc.cluster.local}
          predicates:
            - Path=/api/review/**
          filters:
            - JwtAuth

        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL:http://customer-service.sangsangplus-backend.svc.cluster.local}
          predicates:
            - Path=/api/management/**
          filters:
            - JwtAuth
            - name: AddResponseHeader
              args:
                name: X-Accel-Buffering
                value: "no"  # 프록시 버퍼링 비활성화
            - name: AddResponseHeader
              args:
                name: Cache-Control
                value: "no-cache, no-transform"  # 캐싱 비활성화
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "https://buildingbite.com"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Credentials
                value: "true"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET, POST, PUT, DELETE, OPTIONS"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "Authorization, Content-Type, X-Requested-With"
          metadata:
            response-timeout: 300000  # 300초 타임아웃 (밀리초 단위)
        
        - id: product-details-service
          uri: ${PRODUCT_DETAILS_SERVICE_URL:http://product-details-service.sangsangplus-backend.svc.cluster.local}
          predicates:
            - Path=/api/generation/**
          filters:
            - JwtAuth

        - id: abtest-service
          uri: ${ABTEST_SERVICE_URL:http://abtest-service.sangsangplus-backend.svc.cluster.local}
          predicates:
            - Path=/api/abtest/**
          filters:
            - JwtAuth

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service.sangsangplus-backend.svc.cluster.local}
          predicates:
            - Path=/api/notifications/**
          filters:
            - NotificationJwtFilter
            - name: AddResponseHeader
              args:
                name: X-Accel-Buffering
                value: "no"  # 프록시 버퍼링 비활성화
            - name: AddResponseHeader
              args:
                name: Cache-Control
                value: "no-cache, no-transform"  # 캐싱 비활성화
          metadata:
            response-timeout: 600000  # 600초 타임아웃 (밀리초 단위)

        - id: keycloak_admin
          uri: http://keycloak:8080
          predicates:
            - Path=/admin/**, /realms/**
          filters:
            - StripPrefix=0
      
      # default-filters:
      #   - name: RequestRateLimiter
      #     args:
      #       redis-rate-limiter.replenishRate: 10
      #       redis-rate-limiter.burstCapacity: 20

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/sangsang-plus}

# KeyCloak Configuration
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:sangsang-plus}
  resource: ${KEYCLOAK_CLIENT_ID:gateway-client}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: none


# Service URLs
user-service:
  url: ${USER_SERVICE_URL:http://user-service}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://product-service}

# App Configuration
app:
  oauth2:
    redirectUri: ${FRONTEND_URL:https://buildingbite.com}


logging:
  level:
    com.example.gateway: DEBUG
    org.springframework.security: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.context.annotation: DEBUG
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.boot.web.servlet.support: DEBUG
