server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://user-service.user-service.svc.cluster.local}
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuth

        - id: auth-users-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/users/**
          filters:
            - JwtAuth
            
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://product-service.product-service.svc.cluster.local}
          predicates:
            - Path=/api/products/**
          filters:
            - JwtAuth
        
        - id: review-service
          uri: ${REVIEW_SERVICE_URL:http://review-service.sangsangplus-backend.svc.cluster.local:5001}
          predicates:
            - Path=/api/review/**
          filters:
            - JwtAuth

        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL:http://customer-service.sangsangplus-backend.svc.cluster.local:5001}
          predicates:
            - Path=/api/customer/**
          filters:
            - JwtAuth
        
        - id: product-details-service
          uri: ${PRODUCT_DETAILS_SERVICE_URL:http://product-details-service.sangsangplus-backend.svc.cluster.local:5001}
          predicates:
            - Path=/api/product-details/**
          filters:
            - JwtAuth

        - id: abtest-service
          uri: ${ABTEST_SERVICE_URL:http://abtest-service.sangsangplus-backend.svc.cluster.local:5001}
          predicates:
            - Path=/api/abtest/**
          filters:
            - JwtAuth

        - id: keycloak_admin
          uri: http://keycloak:8080
          predicates:
            - Path=/admin/**, /realms/**
          filters:
            - StripPrefix=0
      
      # default-filters:
      #   - name: RequestRateLimiter
      #     args:
      #       redis-rate-limiter.replenishRate: 10
      #       redis-rate-limiter.burstCapacity: 20

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/sangsang-plus}

# KeyCloak Configuration
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:sangsang-plus}
  resource: ${KEYCLOAK_CLIENT_ID:gateway-client}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: none


# Service URLs
user-service:
  url: ${USER_SERVICE_URL:http://user-service}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://product-service}

# App Configuration
app:
  oauth2:
    redirectUri: ${FRONTEND_URL:https://buildingbite.com}


logging:
  level:
    com.example.gateway: DEBUG
    org.springframework.security: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.context.annotation: DEBUG
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.boot.web.servlet.support: DEBUG