server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 2592000000  # 30 days in milliseconds

# Service URLs
user-service:
  url: http://localhost:8082

logging:
  level:
    com.example.gateway: DEBUG
    org.springframework.security: DEBUG